### ISSUE TITLE
detect if a user has started a session

### ISSUE THREAD

**Issue by SKairinos** [ocadotechnology/codeforlife-contributor-frontend#1]
You will need to create a hook to detect if the user has created a session (i.e. logged in) by looking for the presence of the "session_metadata" cookie. If there cookie is present, the user is logged in.

[We currently do this](https://github.com/ocadotechnology/codeforlife-package-javascript/blob/main/src/hooks/auth.tsx) across our site when detecting if a CFL user has logged in. Create a hook called `useSessionMetdata` which will return the JSON object contained within the cookie (if the user is logged in).

**Comment by SalmanAsh** [comment]
[Refer to this for session metadata](https://github.com/ocadotechnology/codeforlife-contributor-backend/blob/209b80281aa34401c0cdc815848681b31cb548ca/api/views/session.py#L44)

**Comment by SalmanAsh** [comment]
One way to test this:
-Create a temporary test component. 
-Use useEffect to simulate setting a cookie.
-Verify by calling useSessionMetadata() if cookie is detected
<img width="609" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUp2Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b9494f1cdb7868d54e0ce112bff8992e67470637/image.png" alt="image.png" />
