### ISSUE TITLE
create endpoints definitions

### ISSUE THREAD

**Issue by SKairinos** [ocadotechnology/codeforlife-contributor-frontend#2]
Create the API endpoint definitions on the frontend. [See](https://github.com/ocadotechnology/codeforlife-portal-frontend/tree/development/src/api) examples of how to do this on the portal-frontend service.

**Comment by SalmanAsh** [comment]
Don't think we need the endpoint for [check_signed](https://github.com/ocadotechnology/codeforlife-contributor-backend/blob/8d35b8a5ed6741c89e01982d00d2d0c5f2412fb9/api/views/agreement_signature.py#L44) on the frontend so I left it out. Correct me if I'm wrong, please.

**Comment by SKairinos** [comment]
We do need it. It will be called after the user logs in and navigates to the agreement signature page. If they have not signed the latest agreement, they will be prompted to do so.

**Comment by SalmanAsh** [comment]
There may be some API calls to the backend ([Pages](https://github.com/ocadotechnology/codeforlife-contributor-frontend/tree/7e75d3ac915e93341ac8a8f3e93b87f9f09cd279/src/pages)) that are not needed for this task. Those are only testing purposes.
