### ISSUE TITLE
login page

### ISSUE THREAD

**Issue by SKairinos** [ocadotechnology/codeforlife-contributor-frontend#3]
Create the login page. This should just have the CFL log and a "Log in with GitHub" button below in the middle of the screen.

Should look like similar to this:
<img width="951" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHhCQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--97e046561ee14f30daa0d83455096ea3f729ac60/image.png" alt="image.png" />
 

Clicking the button should:
1. open the GH site where contributors can "authorise" CFL to have access to their GH user account.
2. after the user click authorise, they should be redirected back (callback url) to login page on the front end. This will add the search param "code" to the login page url (e.g. ".../login?code=abc").
3.  grab this search param and use it to call the login endpoint on the the backend.
4.  once successfully logged in, redirect the contributor to the "/agreement-signatures" page.

**Comment by SalmanAsh** [comment]
To make it work locally, you need the following fields:
- GH_CLIENT_ID
- GH_CLIENT_SECRET

**Comment by SalmanAsh** [comment]
Two changes were required in contributor-backend:

1. `return Contributor.objects.get_or_create(
  File "/codeforlife-workspace/codeforlife-contributor-backend/.venv/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/codeforlife-workspace/codeforlife-contributor-backend/.venv/lib/python3.8/site-packages/django/db/models/query.py", line 583, in get_or_create
    params = self._extract_model_params(defaults, **kwargs)
  File "/codeforlife-workspace/codeforlife-contributor-backend/.venv/lib/python3.8/site-packages/django/db/models/query.py", line 634, in _extract_model_params
    raise exceptions.FieldError(
django.core.exceptions.FieldError: Invalid field name(s) for model Contributor: 'bio', 'blog', 'company', 'created_at', 'events_url', 'followers', 'followers_url', 'following', 'following_url', 'gists_url', 'gravatar_id', 'hireable', 'login', 'node_id', 'notification_email', 'organizations_url', 'public_gists', 'public_repos', 'received_events_url', 'repos_url', 'site_admin', 'starred_url', 'subscriptions_url', 'twitter_username', 'type', 'updated_at', 'url'.`

**Comment by SalmanAsh** [comment]
![image](https://github.com/user-attachments/assets/a4e2a488-96f1-41f4-a0bf-12e431d3df78)

**Comment by SalmanAsh** [comment]
![Image](https://github.com/user-attachments/assets/3c687989-7118-4c42-b9ff-f7606835f85e)

Run front-end on this port or github won't receive the authentication request.
